<?php
/**
 * Copyright © Monsoon Consulting. All rights reserved.
 * See LICENSE_MONSOON.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
?>
<button id="ad2hs-prompt" class="action primary ad2hs-prompt" style="display: none"
    data-mage-init='{ "Monsoon_Pwa/js/ad2hs-prompt": {}}'>
    <?=$escaper->escapeHtml(__('Add to Home Screen')) ?>
</button>
