<?php
/**
 * Copyright © Monsoon Consulting. All rights reserved.
 * See LICENSE_MONSOON.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $viewModel Monsoon\Pwa\ViewModel\ServiceWorker */

$viewModel = $block->getViewModel();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Monsoon_Pwa/js/registration": {
                "path": "<?= $block->escapeUrl($viewModel->getServiceWorkerPath())?>"
            }
        }
    }
</script>
