<?php
/**
 * Copyright © Monsoon Consulting. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $viewModel Monsoon\Pwa\ViewModel\ServiceWorker */

$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isUnregisterAllowed()): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Monsoon_Pwa/js/unregister": {}
        }
    }
</script>
<?php endif ?>
