<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 * @var $escaper \Magento\Framework\Escaper
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt()
?>
<a
    class="w-64 block"
    href="<?= $escaper->escapeUrl($block->getUrl('')) ?>"
    title="<?= $escaper->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $escaper->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
        <?= $block->getLogoWidth() ? 'width="' . $escaper->escapeHtmlAttr($block->getLogoWidth()) . '"' : '' ?>
        <?= $block->getLogoHeight() ? 'height="' . $escaper->escapeHtmlAttr($block->getLogoHeight()) . '"' : '' ?>
    />
</a>
