<?php
/**
 * Copyright © Monsoon Consulting. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
?>
<button id="ad2hs-prompt" class="btn-primary w-full sticky bottom-0 ad2hs-prompt" style="display: none">
    <?= $escaper->escapeHtml(__('Add to Home Screen')) ?>
</button>

<script>
    window.addEventListener('beforeinstallprompt', (e) => {

        e.preventDefault();

        const addBtn = document.getElementById("ad2hs-prompt");
        let deferredPrompt = e;

        addBtn.style.display = 'block';

        addBtn.addEventListener('click', (e) => {
            // hide our user interface that shows our A2HS button
            addBtn.style.display = 'none';
            // Show the prompt
            deferredPrompt.prompt();
            // Wait for the user to respond to the prompt
            deferredPrompt.userChoice.then((choiceResult) => {
                if (choiceResult.outcome === 'accepted') {
                    console.log('User accepted the A2HS prompt');
                } else {
                    console.log('User dismissed the A2HS prompt');
                }
                deferredPrompt = null;
            });
        });
    });
</script>
